# Generated by Django 2.2.4 on 2019-08-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_auto_20190828_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveField(
            model_name='task',
            name='dateCreated',
        ),
    ]
