# Generated by Django 2.2.4 on 2020-03-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_auto_20190829_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
